CREATE USER app_user WITH PASSWORD 'app_password' CREATEDB;
CREATE DATABASE app_db;
GRANT ALL PRIVILEGES ON DATABASE app_db TO app_user;

\c app_db;

GRANT ALL ON SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO app_user;

CREATE TABLE items (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    price INTEGER NOT NULL
);

GRANT ALL PRIVILEGES ON TABLE items TO app_user;
GRANT USAGE, SELECT ON SEQUENCE items_id_seq TO app_user;